cacheFolder: ./.yarn/cache

enableColors: true

enableScripts: true # This should be `false` for security reasons

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard
  - code: YN0004
    level: discard

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
    spec: "https://github.com/mskelton/yarn-plugin-outdated/raw/v3.0.2/bundles/@yarnpkg/plugin-outdated.js"
