name: Test Master

on:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      branch: master

  unit-tests:
    needs: build
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      branch: master

  lint:
    needs: build
    uses: ./.github/workflows/reusable-lint.yml
    with:
      branch: master

  notify-on-failure:
    name: Notify Slack on failure
    runs-on: ubuntu-latest
    needs: [unit-tests, lint]
    steps:
      - name: Notify Slack on failure
        uses: act10ns/slack@v2.0.0
        if: failure()
        with:
          status: ${{ job.status }}
          channel: '#updates-build-alerts'
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: Master branch (build or test or lint) failed (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
