name: Build, unit test and lint branch

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/build-and-cache
        with:
          cacheKey: ${{ github.sha }}:build

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        target: [backend, frontend, nodes]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/unit-tests
        with:
          cacheKey: ${{ github.sha }}:build
          target: ${{ matrix.target }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        target: [backend, frontend, nodes]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ github.sha }}
      - uses: ./.github/actions/lint
        with:
          cacheKey: ${{ github.sha }}:build
          target: ${{ matrix.target }}
