name: Build, unit test and lint branch

on:
  pull_request:

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      branch: ${{ inputs.branch }}

  unit-tests:
    needs: build
    uses: ./.github/workflows/reusable-unit-tests.yml
    with:
      branch: ${{ inputs.branch }}

  lint:
    needs: build
    uses: ./.github/workflows/reusable-lint.yml
    with:
      branch: ${{ inputs.branch }}
