name: 'Release: PR Checks'

on:
  push:
    branches:
      - 'release-pr/*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: corepack enable
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run typecheck
        run: pnpm typecheck

      - name: Cache build artifacts
        uses: actions/cache/save@v4.0.0
        with:
          path: ./packages/**/dist
          key: ${{ github.sha }}-release-pr:build

  db-tests:
    name: DB tests
    uses: ./.github/workflows/db-tests-reusable.yml
    needs: build
    with:
      cacheKey: ${{ github.sha }}-release-pr:build

  e2e-tests:
    name: E2E Tests
    uses: ./.github/workflows/e2e-reusable.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}
      user: ${{ 'Release' }}
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
