name: Checkout and Build

on:
  workflow_call:
    inputs:
      branch:
        description: 'GitHub branch to build'
        type: string
        required: true

jobs:
  build:
    name: Checkout and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - uses: pnpm/action-setup@v2.4.0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18.x

      - name: Setup pnpm store cache
        uses: actions/cache@v3.3.1
        with:
          path: |
            /home/runner/.pnpm-store
            /github/home/.pnpm-store
          key: pnpm-store-cache

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Cache build artifacts
        uses: actions/cache/save@v3.3.1
        with:
          path: ./packages
          key: build-${{ github.sha }}
