name: Runs unit tests for a given ref

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'GitHub ref to test.'
        required: false
        default: 'master'
        type: string
      prNumber:
        description: 'PR number to run tests for.'
        required: false
        type: number

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.compute-branch.outputs.branch }}
    steps:
      - name: Compute branch
        id: compute-branch
        run: |
          BRANCH_NAME=""
          if [[ "${{ inputs.prNumber }}" != "" && "${{ inputs.prNumber }}" != "null" ]]; then
            BRANCH_NAME="refs/pull/${{ inputs.prNumber }}/merge"
          else
            BRANCH_NAME="${{ inputs.ref }}"
          fi
          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT

  build:
    name: Build
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ needs.prepare.outputs.branch }}
      - uses: ./.github/actions/build-and-cache
        with:
          cacheKey: ${{ needs.prepare.outputs.branch }}:build

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    needs: [prepare, build]
    strategy:
      matrix:
        target: [backend, frontend, nodes]
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          ref: ${{ needs.prepare.outputs.branch }}
      - uses: ./.github/actions/unit-tests
        with:
          cacheKey: ${{ needs.prepare.outputs.branch }}:build
          target: ${{ matrix.target }}
